# Generated by Django 4.2.3 on 2023-07-10 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('product', '0002_productdata_quantity'),
        ('stage', '0001_initial'),
        ('process', '0002_alter_processdata_productname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barcode',
            fields=[
                ('barcode', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=13)),
                ('placeName', models.CharField(choices=[('start', 'start'), ('end', 'end'), ('qa', 'qa'), ('rework', 'rework')], max_length=6)),
                ('timestamp', models.DateTimeField()),
                ('processNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.processdata')),
                ('productName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productdata')),
                ('stageName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.listofstages')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.userdata')),
            ],
        ),
        migrations.CreateModel(
            name='Permanent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permanent', models.CharField(max_length=13)),
                ('barcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcode.barcode')),
            ],
        ),
    ]
