# Generated by Django 4.2.3 on 2023-07-10 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productdata_quantity'),
        ('barcode', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcode',
            name='productName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productlist'),
        ),
    ]
