# Generated by Django 4.2.3 on 2023-07-09 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessData',
            fields=[
                ('processNo', models.IntegerField(primary_key=True, serialize=False)),
                ('startingSNo', models.CharField(max_length=12)),
                ('endingSNo', models.CharField(max_length=12)),
                ('maxQuantity', models.IntegerField()),
                ('currentQuantity', models.IntegerField()),
                ('productName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productdata')),
            ],
        ),
    ]
