# Generated by Django 4.2.3 on 2023-07-09 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processdata',
            name='productName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productlist'),
        ),
    ]
