# Generated by Django 4.2.3 on 2023-07-10 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0001_initial'),
        ('product', '0003_remove_productdata_quantity'),
        ('process', '0002_alter_processdata_productname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('processNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='process.processdata')),
                ('productName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productlist')),
                ('stageName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.listofstages')),
            ],
        ),
    ]
