# Generated by Django 4.2.2 on 2023-06-23 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='logout_time',
            field=models.DateTimeField(null=True),
        ),
    ]
