# Generated by Django 4.2.2 on 2023-06-23 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_alter_userlog_logout_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlog',
            name='login_time',
            field=models.DateTimeField(null=True),
        ),
    ]
