# Generated by Django 4.2.2 on 2023-06-23 07:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StageData',
            fields=[
                ('line_code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('line_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('stage_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.stagedata')),
            ],
        ),
    ]
