# Generated by Django 4.2.2 on 2023-06-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stages',
            old_name='stage_id',
            new_name='line_code',
        ),
    ]
