# Generated by Django 4.2.2 on 2023-06-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0003_stages_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stages',
            old_name='stage',
            new_name='place',
        ),
    ]
