# Generated by Django 4.2.2 on 2023-06-30 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0005_alter_stages_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stages',
            name='place',
            field=models.CharField(choices=[('start', 'start'), ('end', 'end'), ('qa', 'qa'), ('rework', 'rework')], default='end', max_length=10),
        ),
    ]
