# Generated by Django 4.2.2 on 2023-07-04 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_rename_name_products_product_name'),
        ('stage', '0006_alter_stages_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_quantity', models.IntegerField()),
                ('current_quantity', models.IntegerField()),
                ('line_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.stagedata')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.products')),
            ],
        ),
    ]
