# Generated by Django 4.2.2 on 2023-07-04 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0007_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='id',
        ),
        migrations.AddField(
            model_name='quantity',
            name='job_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
