# Generated by Django 4.2.2 on 2023-07-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0008_remove_quantity_id_quantity_job_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity',
            name='job_id',
        ),
        migrations.AddField(
            model_name='quantity',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
