# Generated by Django 4.2.2 on 2023-07-04 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0009_remove_quantity_job_id_quantity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
