# Generated by Django 4.2.2 on 2023-07-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0010_alter_quantity_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quantity',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
