# Generated by Django 4.2.2 on 2023-07-04 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0012_remove_quantity_id_quantity_job_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Quantity',
        ),
    ]
