# Generated by Django 4.2.2 on 2023-07-06 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0014_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='quantity',
            name='end_sno',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quantity',
            name='start_sno',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
    ]
