# Generated by Django 4.2.3 on 2023-07-09 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductList',
            fields=[
                ('productName', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('processId', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ProductData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.BooleanField(default=False)),
                ('end', models.BooleanField(default=False)),
                ('qa', models.BooleanField(default=False)),
                ('rework', models.BooleanField(default=False)),
                ('final', models.CharField(choices=[('start', 'start'), ('end', 'end'), ('qa', 'qa'), ('rework', 'rework')], max_length=6)),
                ('productName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productlist')),
                ('stageName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stage.listofstages')),
            ],
        ),
    ]
