# Generated by Django 4.2.3 on 2023-07-10 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_productdata_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdata',
            name='quantity',
        ),
    ]
