# Generated by Django 4.2.2 on 2023-06-23 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Processes',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stages',
            fields=[
                ('ip', models.GenericIPAddressField(primary_key=True, serialize=False)),
                ('stage_id', models.CharField(max_length=4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.processes')),
            ],
        ),
    ]
