# Generated by Django 4.2.2 on 2023-06-23 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stages',
        ),
        migrations.AddField(
            model_name='products',
            name='fg_code',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='products',
            name='product_code',
            field=models.CharField(default=None, max_length=5),
        ),
        migrations.AlterField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
