# Generated by Django 4.2.2 on 2023-06-23 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_delete_stages_products_fg_code_products_product_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='fg_code',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_code',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
