# Generated by Django 4.2.2 on 2023-06-23 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_alter_products_fg_code_alter_products_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='fg_code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_code',
            field=models.CharField(max_length=5),
        ),
    ]
