# Generated by Django 4.2.2 on 2023-06-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_products_process'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processes',
            old_name='name',
            new_name='process',
        ),
    ]
