# Generated by Django 4.2.2 on 2023-06-25 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0007_rename_name_processes_process'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='name',
            new_name='product_name',
        ),
    ]
