# Generated by Django 4.2.2 on 2023-06-30 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stage', '0006_alter_stages_place'),
        ('place', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placedata',
            name='stage',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stage.stagedata'),
        ),
    ]
